#ATTENTION PLEASE RENAME THIS FILE TO config.py AFTER YOU FILL IN YOUR CREDENTIALS
#WE DO NOT TAKE RESPONIBILITY IF YOU LEAK YOUR CONFIG IF YOU DECIDED TO UPLOAD THIS FILE ON THE INTERNET
user="USERNAME"
password="PASSWORD"
host="0.0.0.0"
port=3600
database="DATABASE"